set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
set showcmd
set showmode
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set autoindent
set textwidth=79
set formatoptions=c
set ruler
set number relativenumber
set mouse=a
filetype plugin indent on
syntax on
set t_Co=256
" set cursorline
set autochdir
set noerrorbells
" set visualbell
set background=dark
set hidden

" vim-plug

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'rust-lang/rust.vim'
Plug 'majutsushi/tagbar'
Plug 'ajh17/VimCompletesMe'
Plug 'vim-airline/vim-airline'
Plug 'morhetz/gruvbox'
Plug 'jiangmiao/auto-pairs'
Plug 'bling/vim-bufferline'
call plug#end()

" Do not show buffers on command row
let g:bufferline_echo = 0

colorscheme gruvbox

map <F2> :NERDTreeToggle<CR>
map <F3> :TagbarToggle<CR> 

" higlight column right after max textwidth
set colorcolumn=+1

" Disable vertical line at max string length in NERDTree
autocmd FileType * setlocal colorcolumn=+1
autocmd FileType nerdtree setlocal colorcolumn=""

" Convenient buffer mgmt
set wildchar=<Tab> wildmenu wildmode=full
set wildcharm=<C-Z>
nnoremap gb :ls<CR>:b<Space>

" No arrow keys
nnoremap <up> <nop>
nnoremap <down> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" Arrow keys can switch buffers
nnoremap <up> :bp<CR>
nnoremap <left> :bp<CR>
nnoremap <down> :bn<CR>
nnoremap <right> :bn<CR>

" Move by displayed lines
nnoremap j gj
nnoremap k gk

" Buf switch made easy
nnoremap ` :b <C-Z>

" Unset highlight after search
nnoremap <CR> :noh<CR><CR>

" Unlock delete
:set backspace=indent,eol,start

" Ctags
set tags=tags;/
