#
# ~/.bash_profile
#

if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi

# Editors
export VISUAL=vim
export EDITOR="$VISUAL"

# Bash-specific
export HISTFILESIZE=1000000
export HISTSIZE=1000000
export HISTCONTROL=ignoreboth:erasedups
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Vagrant
export VAGRANT_HOME=$HOME/VM/vagrant.d

# Golang
export GOPATH=$HOME/.go
export PATH=$PATH:$GOPATH/bin

# Dotfiles executables
export PATH=$HOME/.dotfiles/bin:$PATH

# macOS-specific (has to be before GPG because GPG executes its agent in PATH)
if [[ "$OSTYPE" == "darwin"* ]]; then
    export BASH_SILENCE_DEPRECATION_WARNING=1
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi
