#
# ~/.bash_profile
#

if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi

# Editors
export VISUAL=vim
export EDITOR="$VISUAL"

# Bash-specific
export HISTFILESIZE=1000000
export HISTSIZE=1000000
export HISTCONTROL=ignoreboth:erasedups
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Vagrant
export VAGRANT_HOME=$HOME/VM/vagrant.d

# Golang
export GOPATH=$HOME/.go
export PATH=$PATH:$GOPATH/bin

# Dotfiles executables
export PATH=$HOME/.dotfiles/bin:$PATH

# GnuPG
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null

# macOS-specific (type f to show respect)
if [[ "$OSTYPE" == "darwin"* ]]; then
    export BASH_SILENCE_DEPRECATION_WARNING=1
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi
